models:
  warping_spade:
    name: "WarpingSpadeModel"
    predict_type: "ort"
    model_path: "./checkpoints/liveportrait_onnx/warping_spade.onnx"
  motion_extractor:
    name: "MotionExtractorModel"
    predict_type: "ort"
    model_path: "./checkpoints/liveportrait_onnx/motion_extractor.onnx"
  landmark:
    # name: "LandmarkModel"
    name: "LandmarkRunner"
    predict_type: "ort"
    model_path: "./checkpoints/liveportrait_onnx/landmark.onnx"
  face_analysis:
    name: "FaceAnalysisModel"
    predict_type: "ort"
    model_path:
      - "./checkpoints/liveportrait_onnx/retinaface_det_static.onnx"
      - "./checkpoints/liveportrait_onnx/face_2dpose_106_static.onnx"
  app_feat_extractor:
    name: "AppearanceFeatureExtractorModel"
    predict_type: "ort"
    model_path: "./checkpoints/liveportrait_onnx/appearance_feature_extractor.onnx"
  stitching:
    name: "StitchingModel"
    predict_type: "ort"
    model_path: "./checkpoints/liveportrait_onnx/stitching.onnx"
  stitching_eye_retarget:
    name: "StitchingModel"
    predict_type: "ort"
    model_path: "./checkpoints/liveportrait_onnx/stitching_eye.onnx"
  stitching_lip_retarget:
    name: "StitchingModel"
    predict_type: "ort"
    model_path: "./checkpoints/liveportrait_onnx/stitching_lip.onnx"

crop_params:
  src_dsize: 512
  src_scale: 2.3
  src_vx_ratio: 0.0
  src_vy_ratio: -0.125
  dri_scale: 2.2
  dri_vx_ratio: 0.0
  dri_vy_ratio: -0.1


infer_params:
  flag_use_half_precision: True
  flag_crop_driving_video: False
  flag_lip_zero: True
  flag_eye_retargeting: False
  flag_lip_retargeting: False
  flag_stitching: True
  flag_relative_motion: True
  flag_pasteback: True
  flag_do_crop: True
  flag_do_rot: True

  # NOT EXPOERTED PARAMS
  lip_zero_threshold: 0.03 # threshold for flag_lip_zero
  anchor_frame: 0 # TO IMPLEMENT
  mask_crop_path: "./assets/mask_template.png"

  source_max_dim: 1280 # the max dim of height and width of source image
  source_division: 2 # make sure the height and width of source image can be divided by this number